In [3]:
import numpy as np

https://www.youtube.com/watch?v=LG8lbm_W380

https://github.com/rohan-paul/MachineLearning-DeepLearning-Code-for-my-YouTube-Channel/blob/master/Computer_Vision/run_length_encoding.ipynb

In [4]:



def rle_encode(img):
    '''
    img: numpy array, 1 - mask, 0 - background
    Returns run length as string formated
    '''
    pixels = img.flatten()
    pixels = np.concatenate([[0], pixels, [0]])
    runs = np.where(pixels[1:] != pixels[:-1])[0] + 1
    runs[1::2] -= runs[::2]
    return ' '.join(str(x) for x in runs)

In [19]:
def rle_decode(mask_rle, shape):
    '''
    mask_rle: run-length as string formated (start length)
    shape: (height,width) of array to return 
    Returns numpy array, 1 - mask, 0 - background

    '''
    s = mask_rle.split()
    print(s, 's')
    starts, lengths = [np.asarray(x, dtype=int) for x in (s[0:][::2], s[1:][::2])]
    print(starts, lengths)
    starts -= 1

In [20]:
img = np.array([[0, 0, 0, 0, 1, 0],
 [0, 0, 0, 1, 1, 1],
 [0, 0, 1, 1, 1, 0],
 [0, 0, 1, 1, 0, 0]])
rle_decode(rle_encode(img), (4,4))

['5', '1', '10', '3', '15', '3', '21', '2'] s
[ 5 10 15 21] [1 3 3 2]


In [22]:
display(1)

1

In [41]:
img = np.array([[1,0,0,1],[1,1,1,1],[0,1,1,0],[0,0,0,0]])
img = np.array([[0, 0, 0, 0, 1, 0],
 [0, 0, 0, 1, 1, 1],
 [0, 0, 1, 1, 1, 0],
 [0, 0, 1, 1, 0, 0]])
pixels = img.flatten()

In [43]:
rle_encode(img)

'5 1 10 3 15 3 21 2'

In [36]:
pixels = np.concatenate([[0], pixels, [0]])
pixels 

array([0, 0, 0, 1, 1, 0])

In [37]:
runs = np.where(pixels[1:] != pixels[:-1])[0] + 1
runs

array([3, 5], dtype=int64)

In [38]:
runs[1::2] -= runs[::2]

In [39]:
runs

array([3, 2], dtype=int64)

In [40]:
' '.join(str(x) for x in runs)

'3 2'